### ISSUE TITLE
[Feature]Very good project, hope to support more features

### ISSUE THREAD

**Issue by Andrea-lyz** [botbahlul/pyvosklivesubtitle#1]
For example
memorized pre-selected language options (need to reselect language each time you start the program)
History transcription
Save transcriptions as text
Caption hover window with movable position
Thank you for your work.

**Comment by botbahlul** [comment]
any suggestion for this?
https://github.com/botbahlul/pyvosklivesubtitle/releases/download/pyvosklivesubtitle-0.1.2/pyvosklivesubtitle-0.1.2.zip

**Comment by Andrea-lyz** [comment]
> 有什么建议吗？ https://github.com/botbahlul/pyvosklivesubtitle/releases/download/pyvosklivesubtitle-0.1.0/pyvosklivesubtitle-0.1.0.zip
there are some problems. . .

![屏幕截图 2023-04-09 233901](https://user-images.githubusercontent.com/52863141/230797694-8d5b696a-853e-444b-b214-d93c866ab3c3.png)

**Comment by botbahlul** [comment]
Download those small models manually from https://alphacephei.com/vosk/models then extract them to "/home/username/.cache/vosk" (if you're on Linux) and "C:\Users\Username\\.cache\vosk\" (if you're on Windows).

![image](https://user-images.githubusercontent.com/88623122/230808161-fd81833b-4651-4c0f-9329-6fdb354c3060.png)

Don't forget to put those library files (".dll" for windows, "libvosk.so" for linux) altogether in same folder with pyvls executable (pyvls.exe or pyvls)

![image](https://user-images.githubusercontent.com/88623122/230808460-58ea2a57-443b-4821-a655-514b41329c7c.png)

![image](https://user-images.githubusercontent.com/88623122/230808505-e1da9937-f31c-4695-95d8-62a5e0999425.png)

IT SEEMS THAT YOU'RE TO LAZY TO READ THAT README ON FIRST PAGE OF MY REPO 😁

![image](https://user-images.githubusercontent.com/88623122/230810681-0af12427-22ea-4ab9-811e-d072d4ea4cd2.png)

**Comment by botbahlul** [comment]
Sorry, I have to fix some typos..

https://github.com/botbahlul/pyvosklivesubtitle/releases/download/pyvosklivesubtitle-0.1.2/pyvosklivesubtitle-0.1.2.zip

**Comment by Andrea-lyz** [comment]
> Download those small models manually from https://alphacephei.com/vosk/models then extract them to "/home/username/.cache/vosk" (if you're on Linux) and "C:\Users\Username\.cache\vosk" (if you're on Windows).
> 
> ![image](https://user-images.githubusercontent.com/88623122/230808161-fd81833b-4651-4c0f-9329-6fdb354c3060.png)
> 
> Don't forget to put those library files (".dll" for windows, "libvosk.so" for linux) altogether in same folder with pyvls executable (pyvls.exe or pyvls)
> 
> ![image](https://user-images.githubusercontent.com/88623122/230808460-58ea2a57-443b-4821-a655-514b41329c7c.png)
> 
> ![image](https://user-images.githubusercontent.com/88623122/230808505-e1da9937-f31c-4695-95d8-62a5e0999425.png)
> 
> IT SEEMS THAT YOU'RE TO LAZY TO READ THAT README ON FIRST PAGE OF MY REPO 😁
> 
> ![image](https://user-images.githubusercontent.com/88623122/230810681-0af12427-22ea-4ab9-811e-d072d4ea4cd2.png)

Trust me, I read your README file carefully and set the correct path. In version 0.1.2, it still gives an error.
![230797694-8d5b696a-853e-444b-b214-d93c866ab3c3](https://user-images.githubusercontent.com/52863141/230950727-608fa433-1f7b-46be-ab6d-f0719a40d865.png)
![屏幕截图 2023-04-10 184712](https://user-images.githubusercontent.com/52863141/230950742-59dad260-b5f1-459f-87d1-fb3421df979b.png)
![屏幕截图 2023-04-10 184657](https://user-images.githubusercontent.com/52863141/230950774-b43c0f0e-d930-4e6f-b226-d9e1dbee40d8.png)

In any case, version 0.0.12 works fine.
![屏幕截图 2023-04-10 185145](https://user-images.githubusercontent.com/52863141/230950794-f4fdb119-89dd-4663-9888-ecc2bd398090.png)

**Comment by Andrea-lyz** [comment]
@botbahlul 
UPDATE:
......I found the problem...The packaged version in Releases can't run normally, but through the pyvosklivesubtitle-main of Clone https://github.com/botbahlul/pyvosklivesubtitle.git, and then run pyvls.pyw, everything works. . .
![屏幕截图 2023-04-10 193418](https://user-images.githubusercontent.com/52863141/230959938-5a7ac1ff-358a-4f38-8ec0-4297992dd7d8.png)


suggestion:
1. The subtitle position can be moved, sometimes it is not necessarily watching YouTube.
2. Can I view previous sentences through the configuration window? The current version seems to disappear in the Audio language window immediately after the sentence is broken.
3. There are always some sudden freezes and crashes.

**Comment by botbahlul** [comment]
Are you using Windows 11?
What is your processor and how many RAM you have?

Compiled binary from Releases page runs fine on my Windows 10 PC (I5-3340M CPU @2.7GHz and 16GB RAM).

I've never tested it yet on any Windows 11.

I'll try to add element to show overall transcriptions on next releases.

**Comment by Andrea-lyz** [comment]
> Are you using Windows 11? What is your processor and how many RAM you have?
> 
> Compiled binary from Releases page runs fine on my Windows 10 PC (I5-3340M CPU @2.7GHz and 16GB RAM).
> 
> I've never tested it yet on any Windows 11.
> 
> I'll try to add element to show overall transcriptions on next releases.

Thank u.
But I use win10 like you, core i7-9750H 2.6ghz 16GB DDR4 RAM.
I don't know why sometimes it freezes or crashes when I click start or stop to exit.

**Comment by botbahlul** [comment]
Please let me know if you're still get bugs
https://github.com/botbahlul/pyvosklivesubtitle/releases/download/pyvosklivesubtitle-0.1.3/pyvosklivesubtitle-0.1.3.zip
