### ISSUE TITLE
win11

### ISSUE THREAD

**Issue by ccybc** [botbahlul/pyvosklivesubtitle#2]
The executable file compiled on Win11 reports an error and cannot be run

**Comment by ccybc** [comment]
Traceback (most recent call last):
  File "pyvls.pyw", line 1600, in stop_ffmpeg_windows
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyvls.pyw", line 3519, in <module>
  File "pyvls.pyw", line 2598, in main
  File "pyvls.pyw", line 1619, in stop_ffmpeg_windows
  File "pyvls.pyw", line 2370, in show_error_messages
NameError: name 'main_window' is not defined

**Comment by ccybc** [comment]
I used a lot of your software, none of them worked, and they all went wrong

**Comment by botbahlul** [comment]
which version is it?
it looks like you're not using the latest version

![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/f82167e2-be9e-4d86-95d2-bb99fcd5adba)

please use latest version
If you're still get some troubles you can try to install python and install this app with pip
```
pip install pyvosklivesubtitle
```

I've deleted some buggy releases
let me know others, and I'll delete them

**Comment by ccybc** [comment]
The latest version 0.16 I used，I tested all the versions，Only 0.13 of them can be used，0.15 and 0.16 cannot be opened, and an error is reported，The Android version is very stable to use，YOUR VERSION OF PYTHON AND JAVA NEVER RUNS，I HAVE THE JAVA RUNTIME INSTALLED, BUT NOT THE PYTHON RUNTIME

**Comment by ccybc** [comment]
Only python 0.13 can run, Java Edition and other pythons have failed

**Comment by ccybc** [comment]
I don't know what the problem is？，Do I need to install the Python runtime to run the compiled exe program?

**Comment by ccybc** [comment]
The system is the latest version of WIN11 and has been successfully configured for recording

**Comment by botbahlul** [comment]
The latest version now is 0.1.12 (just uploaded it) :
https://github.com/botbahlul/pyvosklivesubtitle/releases/download/pyvosklivesubtitle-0.1.12/pyvosklivesubtitle-0.1.12.zip

It seems that I need to reconfigure mypyinstaller.bat file if a user doesn't want to install python.

If you have installed python runtime I'm pretty sure most of my releases will work. But please use python version between 3.8.12  to 3.10.4. I can't guarantee it will run on another versions.

Which JRE version do you use?
I developed java version with Oracle Java v1.8.0_351.
If you use different version I'm not sure it will work.
And remember to install those fonts I included in compressed zip file of the release file (extract them into c:\windows\fonts)

**Comment by ccybc** [comment]
Traceback (most recent call last):
  File "pyvls.pyw", line 1564, in stop_ffmpeg_windows
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyvls.pyw", line 3450, in <module>
  File "pyvls.pyw", line 2532, in main
  File "pyvls.pyw", line 1583, in stop_ffmpeg_windows
  File "pyvls.pyw", line 2331, in show_error_messages
NameError: name 'main_window' is not defined

**Comment by ccybc** [comment]
The latest 0.1.12 and python installed

**Comment by ccybc** [comment]
![屏幕截图 2023-05-19 134725](https://github.com/botbahlul/pyvosklivesubtitle/assets/133444503/58c14e92-47c6-4a8b-a4f6-40fbfb8547f3)

**Comment by ccybc** [comment]
https://zhuanlan.zhihu.com/p/150371648
There seems to be a solution to the problem here

**Comment by ccybc** [comment]
Is it that our computers are different，Mine is a Chinese system, so UTF-8 encoding is not universal?

**Comment by ccybc** [comment]
![屏幕截图 2023-05-19 142538](https://github.com/botbahlul/pyvosklivesubtitle/assets/133444503/60621663-749d-4758-92b3-8ad3742ba752)

**Comment by botbahlul** [comment]
it seems that you forgot to put those ffmpeg.exe and ffprobe.exe into c:\windows\system32

have you done that?

BTW, I just upload version 0.1.13
https://github.com/botbahlul/pyvosklivesubtitle/releases/download/pyvosklivesubtitle-0.1.13/pyvosklivesubtitle-0.1.13.zip

https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/44f0936f-1647-478d-b5d4-5784c2a94de6
