### ISSUE TITLE
Doesn't work using Python 3.10.4 - 64 bits, and Win 10. Please help me :)

### ISSUE THREAD

**Issue by d4nfy** [botbahlul/pyvosklivesubtitle#3]
I tried many things to fix it, first with Py 11, Py 3.8.3. Currently on Py 3.10.4.
![Capture d’écran 2023-05-31 204341](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/4b33686a-6d8c-43da-8fb5-48bc679f33df)
I tried to install by pip because i have mistakes with last compiled version (and the two previous versions too). In the folder, this is the 0.1.14 compiled and clone version of Git repository.

![merged-with-compilated](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/08c9051b-75c3-452b-b378-6bf7915afc83)
![merged-with-compilated-2](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/3cf8ebe4-9897-4016-a322-f54ebaa09d6d)

Then, the error with the .pyw file : 
![IDLE-Shell-3-10-4](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/9b85da56-bb2b-4bb3-abee-c10039b423a4)

With command prompt, successfully installed with Py 3.10.4 but error with main_window (I already installed manual languages \.cache\vosk and ffmpeg in system32)  : 

![cmd-installed](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/03c5d205-3f6b-48dd-bc01-e7e1184bb360)
![cmd-error](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/c1746ef2-552f-4b7a-9b69-51e8a8dabbe6)

**Comment by d4nfy** [comment]
specs : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz RAM 16,0 Go

**Comment by botbahlul** [comment]
have you put those ffmpeg.exe and ffprobe.exe into C:\Windows\system32 folder?

**Comment by d4nfy** [comment]
Yup 
![ffprobe-ffmpeg](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/027c8a00-362b-4806-bdcd-f32f23dbb055)
With regard to the last compiled version, here's the error :
![last-version](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/893bf68d-d660-43e5-b00b-d67a160e11ac)

![last-version-2](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/db5024f4-091b-44a4-ae09-88ba65999eec)

**Comment by botbahlul** [comment]
Is C:\Windows\system32 already added to your PATH ENVIRONTMENT?
Can you show me the screenshot when you call ffmpeg from C:\  ?
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/ddd0f032-9a4e-46a7-8862-4ce604091987)
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/29e454fd-c843-4696-a3d2-541c20f740d5)

**Comment by d4nfy** [comment]
Yeah already done.

![yup-2](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/8a9c5e73-fe97-4173-997f-cda2e85e5cbf)
![yup-3](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/7a4b2f0f-00b3-4253-bff4-badb44b26218)

**Comment by botbahlul** [comment]
can you show me your cmd properties dialog window?
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/2cb56713-dd24-4cd9-8d26-00c3074081c5)
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/7dea04e3-7db3-4f40-8e0b-907635973efc)

**Comment by botbahlul** [comment]
can you please save this code below as test.py 

```
import subprocess

tasklist_output = subprocess.check_output(['tasklist'], creationflags=subprocess.CREATE_NO_WINDOW).decode('utf-8')
python_pid = None
for line in tasklist_output.split('\n'):
    if "python" in line:
        print(line)
        python_pid = line.split()[1]
        print("python_pid = %s" %python_pid)
        break
```
and then run it with python 
```
python test.py
```

then show me the screenshot of the output

**Comment by d4nfy** [comment]
Indeed, you were right before the edit, the issue came from UTF-8 not activated in command prompt (i was in Latin, maybe because I'm from France). The exe seems to launch correctly, i'll try it later.

Here's the result for the script you gave me (after correcting UTF-8)
![code-to-test](https://github.com/botbahlul/pyvosklivesubtitle/assets/122362573/dd37da4f-ca06-43d2-98f2-3f4bf7f7cb7b)

**Comment by d4nfy** [comment]
Ok I can open the app thanks. But can't figure out how to configure Line and audio output to use with a headset, my voice is recognized but not the video, I used the same parameters as Readme page and also tried with two virtual cables with VAC and Audio Repeater.

**Comment by botbahlul** [comment]
If you're using a PC with HDMI CONNECTED DEVICE  AND YOU WAN'T TO HEAR THE AUDIO ON THAT HDMI DEVICE:
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/7025bd14-4c5b-4724-9aef-29fc0b5213a5)

Launch Audio Repeater MME, NOT Audio Repeater KS!

![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/b1380d45-83d2-4add-b97b-decd81fd8983)
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/12bbe5d2-019e-4e23-b997-7f79587c1b61)
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/21e31253-9a92-4edf-81cf-7c07f673a015)

But if you're using a LAPTOP WITHOUT HDMI CONNECTED DEVICE change the WAVE OUT of AUDIO REPEATER to your laptops SPEAKER DEVICE, or your HEADPHONE DEVICE
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/6266b142-8443-4058-b6bd-0fbb30411880)

The Wave Out is the device where you want to hear the audio output.

DONT FORGET TO CLICK THAT START BUTTON! IF IT SUCCESFUL, YOU'LL SEE THAT GREEN PROGRESS BAR OF THE QUEUE
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/c956be5c-882b-4058-acbd-ecf754b3a53f)

THEN CLICK MINIMIZE BUTTON, NOT THE CLOSE BUTTON!

**Comment by d4nfy** [comment]
Doesn't work, how do you set up the virtual audio cable? Line/Mic Mode ? It seems that, even with Line 1, only the sound of my mic is detected by your software. Nevertheless, I can hear the live from YouTube in my mic.

**Comment by botbahlul** [comment]
after VAC installed, just select LINE 1 as DEFAULT in PLAYBACK AND in RECORDING device (right click on it and select Set as default)
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/49e7bf96-f586-45cf-a094-7626ddb2966e)

![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/88623122/5db7ce60-4462-4e53-9f51-cf8c2ee10128)

after that I just launch Audio Repeater MMX and set them like those pictures I post above (Line 1 as WAVE IN, and HDMI Speacker as WAVE OUT, or HEADPHONE if I want to hear the output sound from a headphone)

**Comment by botbahlul** [comment]
if VAC doesn't work for you then your only last option is to use Stereo Mix as Default Recording device and Speaker or Headphone as Playback device

There are many VAC similar apps but I haven't tried them yet

**Comment by d4nfy** [comment]
It's working ! Thanks a lot :)
