### ISSUE TITLE
Please help me！It doesn't work

### ISSUE THREAD

**Issue by dr1mforu** [botbahlul/pyvosklivesubtitle#4]
![image](https://github.com/botbahlul/pyvosklivesubtitle/assets/138102146/f6154dca-2df9-49fc-9b13-92c6cf823f82)
What should I do if there is an error and no mode。

**Comment by botbahlul** [comment]
try to install all required modules 1 by 1:
```
pip install pysimplegui
pip install sounddevice
pip install vosk
pip install requests
pip install httpx
pip install streamlink
pip install urllib3
pip install six
pip install pysrt
pip install tqdm
pip install pywin32
pip install pyvosklivesubtitle
```

**Comment by botbahlul** [comment]
> ![image](https://user-images.githubusercontent.com/138102146/249852828-f6154dca-2df9-49fc-9b13-92c6cf823f82.png) What should I do if there is an error and no mode。

try to install all required modules 1 by 1:
```
pip install pysimplegui
pip install sounddevice
pip install vosk
pip install requests
pip install httpx
pip install streamlink
pip install urllib3
pip install six
pip install pysrt
pip install tqdm
pip install pywin32
pip install pyvosklivesubtitle
```
